version: '3.8'

services:
  web:
    build: .
    ports:
      - "443:443"
      - "8080:443"
    depends_on:
      - db
    # You can uncomment this for debug mode to see logs directly
    # command: bash -c "python main.py & gunicorn --bind 0.0.0.0:443 --certfile /app/ssl/cloudflare.pem --keyfile /app/ssl/cloudflare-key.pem main:app"
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ai_planner
      - SECRET_KEY=${SECRET_KEY:-default_secret_key_for_development}
      - APP_URL=${APP_URL:-https://ai-activity-planner.com}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL:-noreply@example.com}
    volumes:
      - .:/app
      - ./ssl/cloudflare.pem:/app/ssl/cloudflare.pem
      - ./ssl/cloudflare-key.pem:/app/ssl/cloudflare-key.pem
    restart: always

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ai_planner
    restart: always

volumes:
  postgres_data:
